package astrodb

enum class Constellation(val abbrev: String, val fullName: String) {
    AND("And", "Andromeda"),
    ANT("Ant", "Antlia"),
    APS("Aps", "Apus"),
    AQR("Aqr", "Aquarius"),
    AQL("Aql", "Aquila"),
    ARA("Ara", "Ara"),
    ARI("Ari", "Aries"),
    AUR("Aur", "Auriga"),
    BOO("Boo", "Bootes"),
    CAE("Cae", "Caelum"),
    CAM("Cam", "Camelopardalis"),
    CNC("Cnc", "Cancer"),
    CVN("CVn", "Canes Venatici"),
    CMA("CMa", "Canis Major"),
    CMI("CMi", "Canis Minor"),
    CAP("Cap", "Capricornus"),
    CAR("Car", "Carina"),
    CAS("Cas", "Cassiopeia"),
    CEN("Cen", "Centaurus"),
    CEP("Cep", "Cepheus"),
    CET("Cet", "Cetus"),
    CHA("Cha", "Chamaeleon"),
    CIR("Cir", "Circinus"),
    COL("Col", "Columba"),
    COM("Com", "Coma Berenices"),
    CRA("CrA", "Corona Australis"),
    CRB("CrB", "Corona Borealis"),
    CRV("Crv", "Corvus"),
    CRT("Crt", "Crater"),
    CRU("Cru", "Crux"),
    CYG("Cyg", "Cygnus"),
    DEL("Del", "Delphinus"),
    DOR("Dor", "Dorado"),
    DRA("Dra", "Draco"),
    EQU("Equ", "Equuleus"),
    ERI("Eri", "Eridanus"),
    FOR("For", "Fornax"),
    GEM("Gem", "Gemini"),
    GRU("Gru", "Grus"),
    HER("Her", "Hercules"),
    HOR("Hor", "Horologium"),
    HYA("Hya", "Hydra"),
    HYI("Hyi", "Hydrus"),
    IND("Ind", "Indus"),
    LAC("Lac", "Lacerta"),
    LEO("Leo", "Leo"),
    LMI("LMi", "Leo Minor"),
    LEP("Lep", "Lepus"),
    LIB("Lib", "Libra"),
    LUP("Lup", "Lupus"),
    LYN("Lyn", "Lynx"),
    LYR("Lyr", "Lyra"),
    MEN("Men", "Mensa"),
    MIC("Mic", "Microscopium"),
    MON("Mon", "Monoceros"),
    MUS("Mus", "Musca"),
    NOR("Nor", "Norma"),
    OCT("Oct", "Octans"),
    OPH("Oph", "Ophiuchus"),
    ORI("Ori", "Orion"),
    PAV("Pav", "Pavo"),
    PEG("Peg", "Pegasus"),
    PER("Per", "Perseus"),
    PHE("Phe", "Phoenix"),
    PIC("Pic", "Pictor"),
    PSC("Psc", "Pisces"),
    PSA("PsA", "Piscis Austrinus"),
    PUP("Pup", "Puppis"),
    PYX("Pyx", "Pyxis"),
    RET("Ret", "Reticulum"),
    SGE("Sge", "Sagitta"),
    SGR("Sgr", "Sagittarius"),
    SCO("Sco", "Scorpius"),
    SCL("Scl", "Sculptor"),
    SCT("Sct", "Scutum"),
    SER("Ser", "Serpens"),
    SEX("Sex", "Sextans"),
    TAU("Tau", "Taurus"),
    TEL("Tel", "Telescopium"),
    TRI("Tri", "Triangulum"),
    TRA("TrA", "Triangulum Australe"),
    TUC("Tuc", "Tucana"),
    UMA("UMa", "Ursa Major"),
    UMI("UMi", "Ursa Minor"),
    VEL("Vel", "Vela"),
    VIR("Vir", "Virgo"),
    VOL("Vol", "Volans"),
    VUL("Vul", "Vulpecula");

    override fun toString(): String {
        return abbrev
    }

    companion object {
        fun parse(conField: String): Constellation {
            try {
                return valueOf(conField.toUpperCase())
            } catch (e: Exception) {
                throw ParseException("unknown constellation '" + conField + "'")
            }
        }
    }
}
