export const objectTypes = [
  { shortName: 'Ast', fullName: 'Asterism' },
  { shortName: 'Asteroid', fullName: 'Asteroid' },
  { shortName: 'Carbon', fullName: 'Carbon Star' },
  { shortName: 'Comet', fullName: 'Comet' },
  { shortName: 'Con', fullName: 'Constellation' },
  { shortName: 'DN', fullName: 'Dark Nebula' },
  { shortName: 'Double', fullName: 'Double/Multiple Star' },
  { shortName: 'EN', fullName: 'Emission Nebula' },
  { shortName: 'Gal', fullName: 'Galaxy' },
  { shortName: 'GCl', fullName: 'Globular Cluster' },
  { shortName: 'Moon', fullName: 'Moon / Lunar feature' },
  { shortName: 'OCl', fullName: 'Open Cluster' },
  { shortName: 'Planet', fullName: 'Planet' },
  { shortName: 'PN', fullName: 'Planetary Nebula' },
  { shortName: 'Q', fullName: 'Quasar' },
  { shortName: 'RN', fullName: 'Reflection Nebula' },
  { shortName: 'Star Cloud', fullName: 'Star Cloud' },
  { shortName: 'Sun', fullName: 'Sun' },
  { shortName: 'Supernova', fullName: 'Supernova' },
  { shortName: 'SNR', fullName: 'Supernova Remnant' },
  { shortName: 'Variable', fullName: 'Variable Star' }
]

export const constellations = [
  // RA is the average of the most eastward and most westward RA.
  // Dec is the average of the most northern and most southern declination.
  // Adapted from https://en.wikipedia.org/wiki/IAU_designated_constellations_by_area
  { abbreviation: 'And', fullName: 'Andromeda', ra: '0.8', dec: '37.4' },
  { abbreviation: 'Ant', fullName: 'Antlia', ra: '10.3', dec: '-32.5' },
  { abbreviation: 'Aps', fullName: 'Apus', ra: '16.1', dec: '-75.3' },
  { abbreviation: 'Aql', fullName: 'Aquila', ra: '19.7', dec: '3.4' },
  { abbreviation: 'Aqr', fullName: 'Aquarius', ra: '22.3', dec: '-10.8' },
  { abbreviation: 'Ara', fullName: 'Ara', ra: '17.4', dec: '-56.6' },
  { abbreviation: 'Ari', fullName: 'Aries', ra: '2.6', dec: '20.8' },
  { abbreviation: 'Aur', fullName: 'Auriga', ra: '6.1', dec: '42.0' },
  { abbreviation: 'Boo', fullName: 'Bootes', ra: '14.7', dec: '31.2' },
  { abbreviation: 'Cae', fullName: 'Caelum', ra: '4.7', dec: '-37.9' },
  { abbreviation: 'Cam', fullName: 'Camelopardalis', ra: '8.9', dec: '69.4' },
  { abbreviation: 'Cap', fullName: 'Capricornus', ra: '21.0', dec: '-18.0' },
  { abbreviation: 'Car', fullName: 'Carina', ra: '8.7', dec: '-63.2' },
  { abbreviation: 'Cas', fullName: 'Cassiopeia', ra: '1.3', dec: '62.2' },
  { abbreviation: 'Cen', fullName: 'Centaurus', ra: '13.1', dec: '-47.3' },
  { abbreviation: 'Cep', fullName: 'Cepheus', ra: '2.5', dec: '71.0' },
  { abbreviation: 'Cet', fullName: 'Cetus', ra: '1.7', dec: '-7.2' },
  { abbreviation: 'Cha', fullName: 'Chamaeleon', ra: '10.7', dec: '-79.2' },
  { abbreviation: 'Cir', fullName: 'Circinus', ra: '14.6', dec: '-63.0' },
  { abbreviation: 'CMa', fullName: 'Canis Major', ra: '6.8', dec: '-22.1' },
  { abbreviation: 'CMi', fullName: 'Canis Minor', ra: '7.7', dec: '6.4' },
  { abbreviation: 'Cnc', fullName: 'Cancer', ra: '8.6', dec: '19.8' },
  { abbreviation: 'Col', fullName: 'Columba', ra: '5.9', dec: '-35.1' },
  { abbreviation: 'Com', fullName: 'Coma Berenices', ra: '12.8', dec: '23.3' },
  { abbreviation: 'CrA', fullName: 'Corona Australis', ra: '18.6', dec: '-41.1' },
  { abbreviation: 'CrB', fullName: 'Corona Borealis', ra: '15.8', dec: '32.6' },
  { abbreviation: 'Crt', fullName: 'Crater', ra: '11.4', dec: '-15.9' },
  { abbreviation: 'Cru', fullName: 'Crux', ra: '12.4', dec: '-60.2' },
  { abbreviation: 'Crv', fullName: 'Corvus', ra: '12.4', dec: '-18.4' },
  { abbreviation: 'CVn', fullName: 'Canes Venatici', ra: '13.1', dec: '40.1' },
  { abbreviation: 'Cyg', fullName: 'Cygnus', ra: '20.6', dec: '44.5' },
  { abbreviation: 'Del', fullName: 'Delphinus', ra: '20.7', dec: '11.7' },
  { abbreviation: 'Dor', fullName: 'Dorado', ra: '5.2', dec: '-59.4' },
  { abbreviation: 'Dra', fullName: 'Draco', ra: '15.1', dec: '67.0' },
  { abbreviation: 'Equ', fullName: 'Equuleus', ra: '21.2', dec: '7.8' },
  { abbreviation: 'Eri', fullName: 'Eridanus', ra: '3.3', dec: '-28.8' },
  { abbreviation: 'For', fullName: 'Fornax', ra: '2.8', dec: '-31.6' },
  { abbreviation: 'Gem', fullName: 'Gemini', ra: '7.1', dec: '22.6' },
  { abbreviation: 'Gru', fullName: 'Grus', ra: '22.5', dec: '-46.4' },
  { abbreviation: 'Her', fullName: 'Hercules', ra: '17.4', dec: '27.5' },
  { abbreviation: 'Hor', fullName: 'Horologium', ra: '3.3', dec: '-53.3' },
  { abbreviation: 'Hya', fullName: 'Hydra', ra: '11.6', dec: '-14.5' },
  { abbreviation: 'Hyi', fullName: 'Hydrus', ra: '2.3', dec: '-70.0' },
  { abbreviation: 'Ind', fullName: 'Indus', ra: '22.0', dec: '-59.7' },
  { abbreviation: 'Lac', fullName: 'Lacerta', ra: '22.5', dec: '46.0' },
  { abbreviation: 'Leo', fullName: 'Leo', ra: '10.7', dec: '13.1' },
  { abbreviation: 'Lep', fullName: 'Lepus', ra: '5.6', dec: '-19.0' },
  { abbreviation: 'Lib', fullName: 'Libra', ra: '15.2', dec: '-15.2' },
  { abbreviation: 'LMi', fullName: 'Leo Minor', ra: '10.2', dec: '32.1' },
  { abbreviation: 'Lup', fullName: 'Lupus', ra: '15.2', dec: '-42.7' },
  { abbreviation: 'Lyn', fullName: 'Lynx', ra: '8.0', dec: '47.5' },
  { abbreviation: 'Lyr', fullName: 'Lyra', ra: '18.9', dec: '36.7' },
  { abbreviation: 'Men', fullName: 'Mensa', ra: '5.4', dec: '-77.5' },
  { abbreviation: 'Mic', fullName: 'Microscopium', ra: '21.0', dec: '-36.3' },
  { abbreviation: 'Mon', fullName: 'Monoceros', ra: '7.1', dec: '0.3' },
  { abbreviation: 'Mus', fullName: 'Musca', ra: '12.6', dec: '-70.2' },
  { abbreviation: 'Nor', fullName: 'Norma', ra: '15.9', dec: '-51.4' },
  { abbreviation: 'Oct', fullName: 'Octans', ra: '23.0', dec: '-82.2' },
  { abbreviation: 'Oph', fullName: 'Ophiuchus', ra: '17.4', dec: '-7.9' },
  { abbreviation: 'Ori', fullName: 'Orion', ra: '5.6', dec: '5.9' },
  { abbreviation: 'Pav', fullName: 'Pavo', ra: '19.6', dec: '-65.8' },
  { abbreviation: 'Peg', fullName: 'Pegasus', ra: '22.7', dec: '19.5' },
  { abbreviation: 'Per', fullName: 'Perseus', ra: '3.2', dec: '45.0' },
  { abbreviation: 'Phe', fullName: 'Phoenix', ra: '0.9', dec: '-48.6' },
  { abbreviation: 'Pic', fullName: 'Pictor', ra: '5.7', dec: '-53.5' },
  { abbreviation: 'PsA', fullName: 'Piscis Austrinus', ra: '22.3', dec: '-30.6' },
  { abbreviation: 'Psc', fullName: 'Pisces', ra: '0.5', dec: '13.7' },
  { abbreviation: 'Pup', fullName: 'Puppis', ra: '7.3', dec: '-31.2' },
  { abbreviation: 'Pyx', fullName: 'Pyxis', ra: '9.0', dec: '-27.4' },
  { abbreviation: 'Ret', fullName: 'Reticulum', ra: '3.9', dec: '-60.0' },
  { abbreviation: 'Scl', fullName: 'Sculptor', ra: '0.4', dec: '-32.1' },
  { abbreviation: 'Sco', fullName: 'Scorpius', ra: '16.9', dec: '-27.0' },
  { abbreviation: 'Sct', fullName: 'Scutum', ra: '18.7', dec: '-9.9' },
  { abbreviation: 'Ser', fullName: 'Serpens', ra: '17.0', dec: '6.1' },
  { abbreviation: 'Sex', fullName: 'Sextans', ra: '10.3', dec: '-2.6' },
  { abbreviation: 'Sge', fullName: 'Sagitta', ra: '19.7', dec: '18.9' },
  { abbreviation: 'Sgr', fullName: 'Sagittarius', ra: '19.1', dec: '-28.5' },
  { abbreviation: 'Tau', fullName: 'Taurus', ra: '4.7', dec: '14.9' },
  { abbreviation: 'Tel', fullName: 'Telescopium', ra: '19.3', dec: '-51.0' },
  { abbreviation: 'TrA', fullName: 'Triangulum Australe', ra: '16.1', dec: '-65.4' },
  { abbreviation: 'Tri', fullName: 'Triangulum', ra: '2.2', dec: '31.5' },
  { abbreviation: 'Tuc', fullName: 'Tucana', ra: '23.8', dec: '-65.8' },
  { abbreviation: 'UMa', fullName: 'Ursa Major', ra: '11.3', dec: '50.7' },
  { abbreviation: 'UMi', fullName: 'Ursa Minor', ra: '15.0', dec: '77.7' },
  { abbreviation: 'Vel', fullName: 'Vela', ra: '9.6', dec: '-47.2' },
  { abbreviation: 'Vir', fullName: 'Virgo', ra: '13.4', dec: '-4.2' },
  { abbreviation: 'Vol', fullName: 'Volans', ra: '7.8', dec: '-69.8' },
  { abbreviation: 'Vul', fullName: 'Vulpecula', ra: '20.2', dec: '24.4' },
  { abbreviation: '', fullName: 'None', ra: '99', dec: '99.99' }
]